# https://taskfile.dev

version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd/rps/main.go --config=./config/local.yaml

  migrate:
    cmds:
      - go run ./cmd/migrator --migrations-path=./migrations/ --migrations-action={{.CLI_ARGS}}